version: '3.5'

services:
  karma:
    image: ${IMAGE_NAME:-ghcr.io/prymitive/karma}:${IMAGE_TAG:-latest}
    environment:
      HOST:
      PORT:
      KARMA_NAME:
      LOG_LEVEL:
      UI_REFRESH:
      UI_THEME:
      ALERTMANAGER_URI:
      ALERTMANAGER_EXTERNAL_URI: https://${ALERTMANAGER_SUBDOMAIN}.${PUBLIC_HOSTNAME}
      ALERTMANAGER_NAME:
      ALERTMANAGER_INTERVAL:
      ALERTMANAGER_TIMEOUT:
      ALERTMANAGER_PROXY:
    networks:
      metric-net:
      traefik-net:
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE:-true}
        traefik.http.routers.karma.entrypoints: ${TRAEFIK_ENTRYPOINT:-http}
        traefik.http.routers.karma.rule: Host(`${TRAEFIK_SUBDOMAIN:-karma}.${PUBLIC_HOSTNAME}`)
        traefik.http.middlewares.karma-auth.basicauth.users: ${TRAEFIK_AUTH}
        traefik.http.routers.karma.middlewares: karma-auth
        traefik.http.services.karma.loadbalancer.server.port: ${PORT}
        traefik.http.services.karma.loadbalancer.healthcheck.path: ${TRAEFIK_HEALTHCHECK_PATH:-/health}
        traefik.http.services.karma.loadbalancer.healthcheck.interval: ${TRAEFIK_HEALTHCHECK_INTERVAL:-30s}
        traefik.http.services.karma.loadbalancer.healthcheck.headers.authorization: ${TRAEFIK_HEALTHCHECK_AUTH}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-128M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-64M}

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
