version: '3.5'

services:
  karma:
    image: ${IMAGE_NAME:-lmierzwa/karma}:${IMAGE_TAG:-latest}
    environment:
      HOST:
      PORT:
      ALERTMANAGER_URI:
      ALERTMANAGER_EXTERNAL_URI:
      ALERTMANAGER_NAME:
      ALERTMANAGER_TIMEOUT:
    networks:
      metric-net:
      traefik-net:
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.frontend.auth.basic.users: ${UI_AUTH}
        traefik.frontend.rule: Host:${TRAEFIK_SUBDOMAIN:-karma}.${PUBLIC_HOSTNAME}
        traefik.backend: karma
        traefik.port: '${PORT}'
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
